spring:
  cloud:
    stream:
      kafka:
        binder:
          auto-add-partitions: true
      bindings:
        cart-queue:
          destination: card-events
          group: group1
        cart-events: 
          destination: card-queue
          producer:
            partition-count: 2