spring:
  cloud:
    stream:
      kafka:
        binder:
          auto-add-partitions: true
      bindings:
        cart-queue:
          destination: carts2
        cart-events:
          destination: carts