spring:
  cloud:
    stream:
      kafka:
        binder:
          auto-add-partitions: true
      bindings:
        card-queue:
          destination: card-queue
          group: group2
        card-events:
          destination: cart-queue
          producer:
            partition-count: 2